spring:
  jpa:
    database-platform: ${DB_PLATAFORM}
    properties:
      hibernate:
        show_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
      
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
    initialization-mode: ${DB_INIT_MODE}
    
cats:
  breeds:
    url: https://api.thecatapi.com/v1/breeds/
  images:
    url: https://api.thecatapi.com/v1/images/search
    limit:
      hats: 3
      sunglasses: 3
      nocategory: 3
  categories:
    hats: 1
    sunglasses: 4
  
process:
  scheduled:
    dataloadcron: 0 */2 * ? * *
    
logging:
  level:
    root: INFO
    httpclient: 
      wire:  INFO
    org:
      apache:
        http: INFO

server:
  servlet:
    context-path: /thecat

camel:
  component:
    servlet: 
      mapping:
        contextPath: /api/*
        
  springboot:
    main-run-controller: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
