spring:
  jpa:
    database-platform: ${DB_PLATAFORM}
    properties:
      hibernate:
        show_sql: false
        
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
    initialization-mode: ${DB_INIT_MODE}
    
cats:
  breeds:
    url: https://api.thecatapi.com/v1/breeds/
  images:
    url: https://api.thecatapi.com/v1/images/search
    limit:
      hats: 3
      sunglasses: 3
      nocategory: 3
  categories:
    hats: 1
    sunglasses: 4
  
logging:
  level:
    httpclient: 
      wire:  DEBUG
    org:
      apache:
        http: DEBUG